
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth
{
	public partial class AppointmentListFrame
	{
		private global::Zyrenth.Gtksharp.AppointmentList appointmentlist1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zyrenth.AppointmentListFrame
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Zyrenth.AppointmentListFrame";
			// Container child Zyrenth.AppointmentListFrame.Gtk.Container+ContainerChild
			this.appointmentlist1 = new global::Zyrenth.Gtksharp.AppointmentList ();
			this.appointmentlist1.WidthRequest = 100;
			this.appointmentlist1.HeightRequest = 100;
			this.appointmentlist1.Name = "appointmentlist1";
			this.appointmentlist1.SelectedIndex = 0;
			this.Add (this.appointmentlist1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
