
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Stetic.Custom custom1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.custom1 = new global::Stetic.Custom ();
		this.custom1.Name = "custom1";
		this.custom1.Int1 = 0;
		this.custom1.Int2 = 0;
		this.Add (this.custom1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
